name: mlc-a3c-37
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pytorch
  - gym
  - box2d-py
  - gym[Box_2D]
  - torchvision
  - matplotlib
  - imageio
  - tensorboard
  - wandb
